CREATE TABLE IF NOT EXISTS public.level_of_expertise
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT level_of_expertise_pkey PRIMARY KEY (id),
    CONSTRAINT ukjgp89c6fjqxxj1ea8p5cv99j8 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.professionals
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    photo oid,
    level_of_expertise_id bigint NOT NULL,
    specialty_id bigint NOT NULL,
    CONSTRAINT professionals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.specialty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT specialty_pkey PRIMARY KEY (id),
    CONSTRAINT ukb3mbi71pgxc6gfih7pg26h8oc UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.professionals
    ADD CONSTRAINT fk64y1g3l5s1n0nemow9sc3kiv9 FOREIGN KEY (specialty_id)
    REFERENCES public.specialty (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.professionals
    ADD CONSTRAINT fk9rsr4hq173pt64bggg7b7cgre FOREIGN KEY (level_of_expertise_id)
    REFERENCES public.level_of_expertise (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;