CREATE TABLE IF NOT EXISTS public.area_of_expertise
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT area_of_expertise_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.professionals
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    photo oid,
    area_of_expertise_id bigint NOT NULL,
    specialty_id bigint NOT NULL,
    CONSTRAINT professionals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.specialty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT specialty_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.professionals
    ADD CONSTRAINT fk64y1g3l5s1n0nemow9sc3kiv9 FOREIGN KEY (specialty_id)
    REFERENCES public.specialty (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.professionals
    ADD CONSTRAINT fkaph74qn1sd6248u005jt00p16 FOREIGN KEY (area_of_expertise_id)
    REFERENCES public.area_of_expertise (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;